name: 'Convert markdown to HTML'
description: 'Convert all markdown files in a directory to HTML'
author: Cpavrai

branding:
  icon: 'file-text'
  color: 'gray-dark'

inputs:
  directory:
    description: 'Which directory to convert files in'
    required: false
    default: '.'
  args:
    description: 'Which arguments to provide to converter'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16

    - name: Install npm 7
      run: npm i -g npm@7
      shell: sh

    - name: Install ShowDown
      run: npm i -g showdown@2.1.0
      shell: sh

    - name: Run convertion
      run: $GITHUB_ACTION_PATH/script.sh ${{ inputs.directory }} "${{ inputs.args }}"
      shell: sh
